Productos/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='productIndex'),
]

accounts/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views as accountViews

app_name = 'accounts'

urlpatterns = [
    url(r'^signUp/', accountViews.signUp.as_view(), name='signUp'),
    url(r'^login/', accountViews.login_v.as_view(), name='login'),
    url(r'^logout/', accountViews.logout_v.as_view(), name='logout'),
]

orderSystem/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views as orderViews

app_name ='orderSystem'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',orderViews.index,name='index'),
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^app/',orderViews.appIndex,name='appindex'),
    url(r'^supplies/',include('supplies.urls',namespace='supplies')),
    url(r'^products/',include('products.urls',namespace='products')),
]

products/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views as productsViews

app_name = 'Products'

urlpatterns = [
    url(r'^$', productsViews.productIndex.as_view(),name='productsIndex'),
    url(r'^newProduct/',productsViews.newProduct.as_view(),name='newProduct'),
    url(r'^deleteProduct/',productsViews.deleteProduct.as_view(),name='deleteProduct'),
    url(r'^editProduct/',productsViews.editProduct.as_view(),name='editProduct'),
]

supplies/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views as suppliesViews

app_name = 'Supplies'

urlpatterns = [
    url(r'^$', suppliesViews.supplyIndex.as_view(),name='suppliesIndex'),
    url(r'^newSupply/',suppliesViews.newSupply.as_view(),name='newSupply'),
    url(r'^deleteSupply/',suppliesViews.deleteSupply.as_view(),name='deleteSupply'),
    url(r'^editSupply/',suppliesViews.editSupply.as_view(),name='editSupply'),
]

accounts/models.py
from django.db import models

# Create your models here.

products/models.py
from django.db import models
from django.core.validators import MinValueValidator
from supplies.models import *
# Create your models here.


class usesSupply(models.Model):
    supply = models.ForeignKey(Supply,on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0,validators=[MinValueValidator(0)])

    def __str__(self):
        return f'{self.supply} < {self.quantity} >'

class Product(models.Model):
    name = models.CharField(max_length=50)
    cost = models.IntegerField(default=0,validators=[MinValueValidator(0)])
    supplies = models.ForeignKey(usesSupply,on_delete=models.CASCADE, default=None)

    def __str__(self):
        return f'[{self.id}] {self.name}'

supplies/models.py
from django.db import models
from django.core.validators import MinValueValidator

# Create your models here.

class Supply(models.Model):
    name = models.CharField(max_length=50)
    cost = models.IntegerField(default=0,validators=[MinValueValidator(0)])
    description = models.CharField(max_length=100)
    quantity = models.IntegerField(default=0,validators=[MinValueValidator(0)])
    
    def __str__(self):
        return f'[{self.id}] {self.name} : {self.description}'

supplies/forms.py
from django import forms
from .models import *

class newSupplyForm(forms.ModelForm):

    class Meta:
        model = Supply
        fields=['name','cost','description','quantity']

Productos/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return HttpResponse("Products Index")

accounts/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout


class signUp(View):
    def get(self, request, *args, **kwargs):
        form = UserCreationForm()
        data = {'signUp': form}
        return render(request, 'accounts/signup.html', data)

    def post(self, request, *args, **kwargs):
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("appindex")
        else:
            data = {'signUp': form}
            return render(request, 'accounts/signup.html', data)


class login_v(View):
    def get(self, request, *args, **kwargs):
        form = AuthenticationForm()
        data = {'login': form}
        return render(request, 'accounts/login.html', data)

    def post(self, request, *args, **kwargs):
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            return redirect("appindex")
        else:
            data = {'login': form}
            return render(request, 'accounts/login.html', data)


class logout_v(View):
    def post(self, request, *args, **kwargs):
        logout(request)
        return redirect("index")

orderSystem/views.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.http import HttpResponse
from django.shortcuts import render,redirect

def index (request):
    if request.user.is_authenticated:
       return redirect("appindex")
    return render(request,'home/index.html')

@login_required(login_url='/accounts/login/')
def appIndex(request):
    return render(request,'home/appindex.html')

products/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views import View
from .forms import *
from .models import *
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

class productIndex(View):
    def get(self, request, *args, **kwargs):
        products = Product.objects.all()
        data = {'products':products}
        return render(request, 'products/index.html',data)

@method_decorator(login_required,name='dispatch')
class newProduct(View):
    def get(self, request, *args, **kwargs):
        pass
    def post(self, request, *args, **kwargs):
        pass


@method_decorator(login_required,name='dispatch')
class editProduct(View):
    def get(self, request, *args, **kwargs):
        pass
    
    def post(self, request, *args, **kwargs):
        pass


@method_decorator(login_required,name='dispatch')
class deleteProduct(View):
    def post(self, request, *args, **kwargs):
        pass

supplies/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views import View
from .forms import newSupplyForm
from .models import *
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
# Create your views here.


@method_decorator(login_required,name='dispatch')
class supplyIndex(View):
    def get(self, request, *args, **kwargs):
        supplies = Supply.objects.all()
        data = {'supplies':supplies}
        return render(request, 'supplies/index.html',data)


@method_decorator(login_required,name='dispatch')
class newSupply(View):
    def get(self, request, *args, **kwargs):
        form = newSupplyForm()
        data = {'form': form}
        return render(request, 'supplies/newSupply.html',data)
    def post(self, request, *args, **kwargs):
        form = newSupplyForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('appindex')
        else:
            data = {'form': form}
            return render(request, 'supplies/newSupply.html',data)


@method_decorator(login_required,name='dispatch')
class editSupply(View):
    def get(self, request, *args, **kwargs):
        id = request.GET.get("id")
        item = Supply.objects.get(id=id)
        form = newSupplyForm(instance=item)
        data = {'form': form,'id':id}
        return render(request,'supplies/edit.html',data)
    
    def post(self, request, *args, **kwargs):
        id = request.POST.get("id")
        item = Supply.objects.get(id=id)
        form = newSupplyForm(request.POST, instance=item)
        if form.is_valid:
            form.save()
            return redirect('Supplies:suppliesIndex')
        else:
            data = {'form': form}
            return render(request,'supplies/edit.html',data)


@method_decorator(login_required,name='dispatch')
class deleteSupply(View):
    def post(self, request, *args, **kwargs):
        id = request.POST.get("id")
        Supply.objects.get(id=id).delete()
        return redirect('Supplies:suppliesIndex')

templates/accounts/login.html
{%extends "base.html"%}
{% load crispy_forms_tags %}

{%block content%}
<div class="container">
    {%if error%}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>Holy guacamole!</strong> {{error}}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    {%endif%}

    <form method="post" action="{%url 'accounts:login'%}">
        {% csrf_token %}
        {{ login|crispy }}
        <button type="submit" class="btn btn-outline-success">Log In</button>
    </form>
</div>
</div>

{%endblock content%}

templates/accounts/signup.html
{%extends "base.html"%}
{% load crispy_forms_tags %}

{%block content%}
<div class="container">
    {%if error%}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>Holy guacamole!</strong> {{error}}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    {%endif%}

    <form method="post" action="{%url 'accounts:signUp'%}">
        {% csrf_token %}
        {{ signUp|crispy }}
        <button type="submit" class="btn btn-outline-success">Sign Up</button>
    </form>
</div>
</div>

{%endblock content%}

templates/appBase.html
{%load static%}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>Order System</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
    </script>
    <script src="https://kit.fontawesome.com/83d1185aae.js" crossorigin="anonymous"></script>

</head>

<body>


    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #FF9900;">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
                aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{%url 'appindex'%}"><img
                                src="https://i.ya-webdesign.com/images/the-letter-a-png-4.png" width="30" height="30"
                                class="d-inline-block align-top" alt="">
                            Order System</a>
                    </li>
                    {% if user.is_authenticated and request.user.is_superuser%}
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'supplies:suppliesIndex'%}">Supplies</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'products:productsIndex'%}">Products</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Orders</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Clients</a>
                    </li>
                    {%else%}
                    <li class="nav-item">
                        <a class="nav-link" href="#">New Order</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">My Orders</a>
                    </li>
                    {%endif%}
                </ul>
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <form method="post" action="{%url 'accounts:logout'%}">
                            {% csrf_token %}
                            <a class="nav-link" onclick="parentNode.submit();">Log Out</a>
                        </form>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    {% block content %}
    {% endblock content %}

</body>

</html>

templates/base.html
{%load static%}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>Order System</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
    </script>
    <script src="https://kit.fontawesome.com/83d1185aae.js" crossorigin="anonymous"></script>

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #FF9900">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
                aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{%url 'index'%}"><img
                                src="https://i.ya-webdesign.com/images/the-letter-a-png-4.png" width="30" height="30"
                                class="d-inline-block align-top" alt="">
                            Order System</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">About</a>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="{%url 'accounts:login'%}">Login</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{%url 'accounts:signUp'%}">Sign Up</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    {% block content %}
    {% endblock content %}

</body>

</html>

<!--https://i.ya-webdesign.com/images/the-letter-a-png-4.png-->

templates/baseApp.html
{%load staticfiles%}
<!DOCTYPE html>
<html>
  <head>
    <title>OrderSystem</title>
  </head>
  <body>
  <meta charset="UTF-8" />
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />

  {% block content %} {% endblock content %}</body>
</html>

templates/home/appindex.html
{%extends "appBase.html"%}


{%block content%}

{%endblock content%}

templates/home/index.html
{%extends "base.html"%}


{%block content%}


{%endblock content%}

templates/products/index.html
{%extends "appBase.html"%}
{% load crispy_forms_tags %}

{%block content%}
<div class="container">

    <h1>
        <center>Products</center>
    </h1>
    <ul class="list-group">
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Cost</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                {%for item in products%}
                <tr>
                    <td>{{item.name}}</td>
                    <td>{{item.cost}}</td>
                    <td>
                        <form action="/products/editSupply" method="get">
                            <input type="hidden" name="id" value="{{item.id}}">
                            <button type="submit" class="btn btn-outline-warning">
                                <i class="fas fa-edit"></i>
                            </button>
                        </form>
                        <form action="/products/deleteSupply/" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="id" value="{{item.id}}">
                            <button type="submit" class="btn btn-outline-danger">
                                <i class="fas fa-trash-alt    "></i>
                            </button>
                        </form>
                    </td>
                </tr>
                {%endfor%}
            </tbody>
        </table>

    </ul>
    <br>
    <form method="get" action="{%url 'products:newProduct'%}">
        <button type="submit" class="btn btn-primary">New Product</button>
    </form>
</div>
{%endblock content%}

templates/supplies/edit.html
{%extends "appBase.html"%}
{% load crispy_forms_tags %}

{%block content%}
<h1>
    <center>Edit Supply</center>
</h1>
<div class="container">
    <form method="post" action="{%url 'supplies:editSupply'%}">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="hidden" name="id" value="{{id}}">
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>
{%endblock content%}

templates/supplies/index.html
{%extends "appBase.html"%}
{% load crispy_forms_tags %}

{%block content%}
<div class="container">

    <h1>
        <center>Supplies</center>
    </h1>
    <ul class="list-group">
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Cost</th>
                    <th scope="col">Description</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                {%for item in supplies%}
                <tr>
                    <td>{{item.name}}</td>
                    <td>{{item.cost}}</td>
                    <td>{{item.description}}</td>
                    <td>{{item.quantity}}</td>
                    <td>
                        <form action="/supplies/editSupply" method="get">
                            <input type="hidden" name="id" value="{{item.id}}">
                            <button type="submit" class="btn btn-outline-warning">
                                <i class="fas fa-edit"></i>
                            </button>
                        </form>
                        <form action="/supplies/deleteSupply/" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="id" value="{{item.id}}">
                            <button type="submit" class="btn btn-outline-danger">
                                <i class="fas fa-trash-alt    "></i>
                            </button>
                        </form>
                    </td>
                </tr>
                {%endfor%}
            </tbody>
        </table>

    </ul>
    <br>
    <form method="get" action="{%url 'supplies:newSupply'%}">
        <button type="submit" class="btn btn-primary">New Supply</button>
    </form>
</div>
{%endblock content%}

templates/supplies/newSupply.html
{%extends "appBase.html"%}
{% load crispy_forms_tags %}

{%block content%}
<h1>
    <center>New Supply</center>
</h1>
<div class="container">
    <form method="post" action="{%url 'supplies:newSupply'%}">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>
{%endblock content%}